<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    





    <gazebo>
        <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">

        <ros>
            <!-- <namespace>/br</namespace> -->
        </ros>

        <update_rate>50</update_rate>

        <!-- wheels -->
        <left_joint>base_left_wheel_joint</left_joint>
        <right_joint>base_right_wheel_joint</right_joint>
                <!-- <wheel_separation>0.825</wheel_separation>
                <wheel_diameter>0.36</wheel_diameter> -->
        <!-- kinematics -->
        <wheel_separation>${base_radius + wheel_length}</wheel_separation>
        <wheel_diameter>${2*wheel_radius}</wheel_diameter>

        <!-- limits -->
        <max_wheel_torque>20</max_wheel_torque>
        <max_wheel_acceleration>1.0</max_wheel_acceleration>

        <command_topic>cmd_vel</command_topic>

        <!-- output -->
        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
        <publish_wheel_tf>false</publish_wheel_tf>

        <odometry_topic>odom</odometry_topic>
        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>base_footprint</robot_base_frame>

        </plugin>
    </gazebo>

<!--     <gazebo reference="camera_link">
    <sensor type="camera" name="camera_sensor">
        <always_on>true</always_on>
        <update_rate>15.0</update_rate>
        <camera name="camera_sensor">
            <horizontal_fov>1.46608</horizontal_fov>
            <image>
                <width>320</width>
                <height>180</height>
                <format>R8G8B8</format>
            </image>
            <distortion>
                <k1>0.0</k1>
                <k2>0.0</k2>
                <k3>0.0</k3>
                <p1>0.0</p1>
                <p2>0.0</p2>
                <center>0.5 0.5</center>
            </distortion>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
            <ros>
                <!- <namespace>stereo</namespace> ->
                <remapping>~/image_raw:=image_raw</remapping>
                <remapping>~/camera_info:=camera_info</remapping>
            </ros>
            <!- Set camera name. If empty, defaults to sensor name (i.e. "sensor_name") ->
            <camera_name>camera_sensor</camera_name>
            <!- Set TF frame name. If empty, defaults to link name (i.e. "link_name") ->
            <frame_name>camera_link</frame_name>
            <hack_baseline>0.2</hack_baseline>
        </plugin>
    </sensor>
    <material>Gazebo/Green</material>
</gazebo> -->



    <gazebo>
    <plugin name="bytes_joint_state" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <!-- <namespace>/br</namespace> -->
        <remapping>~/out:=joint_states</remapping>
      </ros>
      <update_rate>30</update_rate>
      <joint_name>base_left_wheel_joint</joint_name>
      <joint_name>base_right_wheel_joint</joint_name>
    </plugin>
</gazebo>

</robot>