<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Parameters for mobile base -->
    <xacro:property name="base_length" value ="0.07"/>
    <xacro:property name="base_radius" value ="0.8"/>

    <!-- Parametesr for mobile base wheels -->
    <xacro:property name="wheel_radius" value ="0.18"/>
    <xacro:property name="wheel_length" value ="0.05"/>

    <!-- Parametesr for mobile base caster wheels -->
    <xacro:property name="caster_wheel_radius" value ="0.07"/>
    <xacro:property name="caster_wheel_length" value ="${((base_length / 2) * 2)+(wheel_radius)}"/>
    
    <xacro:property name="lider" value ="0.15"/>

    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.05" />
    <xacro:property name="camera_hight" value="0.1" />



<!-- ********************** Base footprint link and joint ********************** -->
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <origin xyz="0.0 0.0 ${caster_wheel_length}" rpy="0.0 0.0 0.0"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>

<!-- ********************** Base link ********************** -->
    <link name="base_link">

        <visual>
            <origin xyz="0.0 0.0 ${(base_length / 2)}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 ${(base_length / 2)}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}"/>
            </geometry>
        </collision>

        <xacro:cylinder_inertia m="1.0" r="${base_radius}" h="${base_length}" 
                                    xyz="0 0 ${base_length/2}" rpy="0 0 ${pi / 2.0}" />
    </link>

<!-- ********************** Wheel links and joints ********************** -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">

            <visual>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="grey" />
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="0.05" r="${wheel_radius}" h="${wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>
    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <joint name="base_right_wheel_joint" type="continuous">
        <origin xyz="0.0 ${(base_radius)+(wheel_length / 2)} ${-((base_length / 2) * 2)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0.0 1 0.0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <origin xyz="0.0 ${-((base_radius)+(wheel_length / 2))} ${-((base_length / 2) * 2)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0.0 1 0.0"/>
    </joint>

<!-- ********************** caster wheel links and joints ********************** -->
    <xacro:macro name="caster_wheel_link" params="prefix">
        <link name="${prefix}_caster_wheel_link">

            <visual name="caster_wheel_handel">
                <origin xyz="0.0 0.0 ${-((caster_wheel_length-caster_wheel_radius)/2)}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length - caster_wheel_radius}"/>
                </geometry>
            </visual>

            <visual name="caster_wheel">
                <origin xyz="0.0 0.0 ${-((caster_wheel_length/2)*2)+caster_wheel_radius}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 ${-((caster_wheel_length)/2)}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="0.04" r="${caster_wheel_radius}" h="${caster_wheel_length}" 
                                    xyz="0 0 ${-((caster_wheel_length-caster_wheel_radius)/2)}" rpy="0 0 0" />

        </link>
    </xacro:macro>
    <xacro:caster_wheel_link prefix="front" />
    <xacro:caster_wheel_link prefix="back" />

    <joint name="front_caster_wheel_joint" type="fixed">
        <origin xyz="${base_radius-0.1} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="front_caster_wheel_link"/>
    </joint>

    <joint name="back_caster_wheel_joint" type="fixed">
        <origin xyz="${-(base_radius-0.1)} 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="back_caster_wheel_link"/>
    </joint>

<!-- ********************** Imu links and joints ********************** -->
    <link name="imu_link"/>

    <joint name="base_imu_joint" type="fixed">
        <origin xyz="0.0 0.0 ${base_length/2}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

<!-- ********************** Lider links and joints ********************** -->
    <link name="lider_link">
        
        <visual name="">
            <origin xyz="0.0 0.0 ${lider/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${lider} ${lider} ${lider}"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 ${lider/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${lider} ${lider} ${lider}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="0.1" l="${lider}" w="${lider}" h="${lider}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_lider_joint" type="fixed">
        <origin xyz="0.0 0.0 ${base_length}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="lider_link"/>
    </joint>

<!-- ********************** Camera links and joints ********************** -->
    <link name="camera_link">
        
        <visual>
            <origin xyz="0.0 0.0 ${-(camera_hight-0.05)}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_hight}"/>
            </geometry>
            <material name="grey"/>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 ${-(camera_hight-0.05)}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_hight}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="0.1" l="${camera_length}" w="${camera_width}" h="${camera_hight}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>


    <joint name="base_camera_joint" type="fixed">
        <origin xyz="${lider/2} 0.0 ${base_length + lider+(camera_hight)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>
</robot>